version: "3.7"

services:
  rails:
    build:
      context: .
      dockerfile: Dockerfile
    image: thinknetica/is-sample-app
    ports:
    - "80:3000"
    depends_on:
    - postgres
    networks:
    - rails-net
    container_name: is-sample-app    

  postgres:
    environment:
    - POSTGRES_DB=sample_rails_app_development
    - POSTGRES_PASSWORD=password
    image: postgres
    volumes:
    - postgres:/var/lib/postgresql/data
    networks:
    - rails-net
    container_name: is-sample-db

networks:
  rails-net:

volumes:
  postgres:
