production:
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  adapter: postgresql
  encoding: unicode
  host: is-sample-db
  database: sample_rails_app_production
  user: postgres
  password: <%= ENV['POSTGRES_PASSWORD'] %>
